### ISSUE TITLE
form issues

### ISSUE THREAD

**Issue by jleenman** [vasilisvg/blokweb-issues#4]
issue over meerdere formulieren ipv fieldsets of ontbrekende submit of action

- elk formulier heeft minstens 1 submit en 1 action, meerdere filters groepeer je in 1 formulier met fieldsets.

**Comment by vasilisvg** [comment]
Hier een verhaal over submit en action:
https://github.com/vasilisvg/blokweb-issues/blob/master/html/formulieren-html.md#elk-formulier-heeft-een-submit-button-en-een-action

**Comment by jleenman** [comment]
lijkt me goed zo
